clean_filters_calibration:
  name: Clean Filters Calibration
  description: Calibrate clean filters on the Komfovent unit
  target:
    device:
      integration: komfovent

set_operation_mode:
  name: Set Operation Mode
  description: Set the operation mode of the Komfovent unit
  target:
    device:
      integration: komfovent
  fields:
    mode:
      name: Mode
      description: The operation mode to set
      required: true
      selector:
        select:
          options:
            - "off"
            - "air_quality"
            - "away"
            - "normal"
            - "intensive"
            - "boost"
            - "kitchen"
            - "fireplace"
            - "override"
    minutes:
      name: Minutes
      description: Duration in minutes for kitchen, fireplace and override modes (1-300)
      required: false
      selector:
        number:
          min: 1
          max: 300
          mode: box

set_system_time:
  name: Set System Time
  description: Set the system time on the Komfovent unit to match the local time
  target:
    device:
      integration: komfovent
